name: ica11
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0' # Adjusted SDK constraint to be more conventional

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Added core dependencies for your app ---
  sqflite: ^2.3.3 # Updated version
  path: ^1.9.0    # Updated version
  image_picker: ^1.1.2 # Updated version (if you plan to use it)
  # http, flutter_image removed as they're not needed for local assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated version

flutter:
  uses-material-design: true

  # --- CORRECTED: Asset declaration moved here under the 'flutter' key ---
  assets:
    - assets/cards/